spring.application.name=ms

# DataSource Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:my-secret-key}

app.seed.admin.enabled=${SEED_ADMIN_ENABLED:false}
app.seed.admin.username=${SEED_ADMIN_USERNAME:admin}
app.seed.admin.email=${SEED_ADMIN_EMAIL:admin@plus.local}
app.seed.admin.password=${SEED_ADMIN_PASSWORD:admin123}
