package com.pucrs.ms.repositories;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.time.Instant;
import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;

import com.pucrs.ms.domain.refreshtoken.RefreshToken;
import com.pucrs.ms.domain.user.User;
import com.pucrs.ms.domain.user.UserRole;

@DataJpaTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class RefreshTokenRepositoryTest {

    @Autowired
    private RefreshTokenRepository refreshTokenRepository;

    @Autowired
    private TestEntityManager em;

    private User persistedUser() {
        User u = new User("alice", "alice@plus.local", "encoded", UserRole.USER);
        em.persist(u);
        return u;
    }

    private RefreshToken buildToken(String token, User user, Instant expiresAt, Instant revokedAt) {
        RefreshToken rt = new RefreshToken();
        rt.setToken(token);
        rt.setUser(user);
        rt.setCreatedAt(Instant.now());
        rt.setExpiresAt(expiresAt);
        rt.setRevokedAt(revokedAt);
        return rt;
    }

    @Test
    void findByToken_returnsToken_whenTokenExists() {
        User u = persistedUser();
        em.persist(buildToken("abc-123", u, Instant.now().plusSeconds(60), null));
        em.flush();

        Optional<RefreshToken> found = refreshTokenRepository.findByToken("abc-123");

        assertThat(found).isPresent();
        assertThat(found.get().getUser().getEmail()).isEqualTo("alice@plus.local");
    }

    @Test
    void findByToken_returnsEmpty_whenTokenNotFound() {
        assertThat(refreshTokenRepository.findByToken("missing")).isEmpty();
    }

    @Test
    void save_persistsToken_andGeneratesId() {
        User u = persistedUser();
        em.flush();
        RefreshToken rt = buildToken("xyz", u, Instant.now().plusSeconds(60), null);

        RefreshToken saved = refreshTokenRepository.save(rt);

        assertThat(saved).isNotNull();
        // id is generated by Hibernate UUID strategy — populated after persist+flush
        em.flush();
        assertThat(em.getId(saved)).isNotNull();
    }

    @Test
    void uniqueTokenConstraint_isEnforced() {
        User u = persistedUser();
        em.persist(buildToken("duplicate-token", u, Instant.now().plusSeconds(60), null));
        em.flush();

        RefreshToken duplicate = buildToken("duplicate-token", u, Instant.now().plusSeconds(120), null);

        assertThatThrownBy(() -> refreshTokenRepository.saveAndFlush(duplicate))
                .isInstanceOf(DataIntegrityViolationException.class);
    }
}
